version: '3.4'

services:
  hospitalmgt.api:
    image: ${DOCKER_REGISTRY-}hospitalmgtapi
    build:
      context: .
      dockerfile: Services/Hospital Managment/HospitalMgt.API/Dockerfile
  pgadmin:
    image: dpage/pgadmin4

  hospitalmanagmentdb:
   image: postgres

volumes:
  hospitaldb_data:
  pgadmin_data:
    