version: '3.4'

services:
  hospitalmgt.api:
    image: ${DOCKER_REGISTRY-}hospitalmgtapi
    build:
      context: .
      dockerfile: Services/Hospital Managment/HospitalMgt.API/Dockerfile
  laboratory.api:
    image: ${DOCKER_REGISTRY-}laboratoryapi
    build:
      context: .
      dockerfile: Services/Laboratory Information System/LIS.API/Dockerfile
  pgadmin:
    image: dpage/pgadmin4

  hospitalmanagmentdb:
    image: postgres
  lisdb:
    image: mongo

volumes:
  hospitaldb_data:
  pgadmin_data:
  lisdb_data:
    