version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  billingdb:
    image: redis:alpine

  pgadmin:
    image: dpage/pgadmin4

  hospitalmanagmentdb:
    image: postgres

  lisdb:
    image: mongo
  
  doctordb:
    image: postgres
    
  hospitalmgt.api:
    image: ${DOCKER_REGISTRY-}hospitalmgtapi
    build:
      context: .
      dockerfile: Services/Hospital Managment/HospitalMgt.API/Dockerfile

  laboratory.api:
    image: ${DOCKER_REGISTRY-}laboratoryapi
    build:
      context: .
      dockerfile: Services/Laboratory Information System/LIS.API/Dockerfile

  billing.api:
    image: ${DOCKER_REGISTRY-}billingapi
    build:
      context: .
      dockerfile: Services/Billing System/Billing.API/Dockerfile

  practitioner.command.api:
    image: ${DOCKER_REGISTRY-}practitionercommandapi
    build:
      context: .
      dockerfile: Services/Practitioner/Practitioner.API/Dockerfile

  practitioner.query.api:
    image: ${DOCKER_REGISTRY-}practitionerqueryapi
    build:
      context: .
      dockerfile: Services/Practitioner/Practitioner.Query.API/Dockerfile

  lis.grpc:
    image: ${DOCKER_REGISTRY-}lisgrpc
    build:
      context: .
      dockerfile: Services/Laboratory Information System/LIS.Grpc/Dockerfile

volumes:
  hospitaldb_data:
  pgadmin_data:
  lisdb_data:
  portainer_data:
  doctordb_data:
    



