version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  billingdb:
    container_name: billingdb
    restart: always
    ports:
      - "6379:6379"
    
  hospitalmanagmentdb:
    container_name: hospitalmanagmentdb
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=HospitalManagementDb
    ports:
      - "5432:5432"
    volumes:
      - hospitaldb_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@shegermed.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - hospitalmanagmentdb
    volumes:
      - pgadmin_data:/root/.pgadmin

  lisdb:
    container_name: lisdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - lisdb_data:/data/db
  
  doctordb:
    container_name: doctordb
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DoctorInsights
    ports:
      - "5433:5432"
    volumes:
      - doctordb_data:/var/lib/postgresql/data/
  
  hospitalmgt.api:
    container_name: hospitalmgt.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgresConnection=Server=hospitalmanagmentdb;Port=5432;Database=HospitalManagementDb;User Id=admin;Password=admin1234;"
    depends_on:
      - hospitalmanagmentdb
    ports:
      - "8000:80"

  laboratory.api:
    container_name: laboratory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbConnection:ConnectionStrings=mongodb://lisdb:27017/"
    depends_on:
      - lisdb
    ports:
      - "8001:80"

  billing.api:
    container_name: billing.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:RedisConnection=billingdb:6379"
    depends_on:
      - billingdb
    ports:
      - "8002:80"

  practitioner.command.api:
    container_name: practitioner.command.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgresConnection=Server=doctordb;Port=5432;Database=DoctorInsights;User Id=admin;Password=admin1234;"
    depends_on:
      - doctordb
    ports:
      - "8003:80"

  practitioner.query.api:
    container_name: practitioner.query.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgresConnection=Server=doctordb;Port=5432;Database=DoctorInsights;User Id=admin;Password=admin1234;"
      - "GrpcSettings:LaboratoryUrl=lis.grpc"
    depends_on:
      - doctordb
    ports:
      - "8004:80"


  lis.grpc:
    container_name: lis.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbConnection:ConnectionStrings=mongodb://lisdb:27017"
    depends_on:
      - lisdb
    ports:
      - "8005:80"

