version: '3.4'

services:
  envoygateway:
    build: API Gateway/Envoy/
    ports: 
      - "9000:9000"
      - "9001:9001"
    volumes: 
      - ./API Gateway/Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  hospitalmgt.api:
    image: ${DOCKER_REGISTRY-}hospitalmgtapi
    build:
      context: .
      dockerfile: Services/Hospital Managment/HospitalMgt.API/Dockerfile

  pgadmin:
    image: dpage/pgadmin4

  hospitalmanagmentdb:
   image: postgres

volumes:
  hospitaldb_data:
  pgadmin_data:
    