version: '3.4'

services:
  laboratory.api:
    container_name: laboratory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbConnection:ConnectionStrings=mongodb://lisdb:27017"
    depends_on:
      - lisdb
    ports:
      - "8001:80"

  hospitalmgt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgresConnection=Server=hospitalmanagmentdb;Port=5432;Database=HospitalManagementDb;User Id=admin;Password=admin1234;"
    depends_on:
      - hospitalmanagmentdb
    ports:
      - "8000:80"

  hospitalmanagmentdb:
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=HospitalManagementDb
    ports:
      - "5432:5432"
    volumes:
      - hospitaldb_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@shegermed.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - hospitalmanagmentdb
    volumes:
      - pgadmin_data:/root/.pgadmin


  lisdb:
    container_name: lisdb
    restart: always
    ports:
      - "27017:27071"
    volumes:
      - lisdb_data:/data/db
        